### ISSUE TITLE
An indicator on the selected or played chain

### ISSUE THREAD

**Issue by whysofast** [mat1jaczyyy/apollo-studio#256] opened 2019-08-28 06:18 UTC
### Is your feature request related to a problem? Please describe.
I got to search in chains one by one to find the effect that I want to copy or access to make an modification.

### Describe the solution you'd like
An indicator on the selected or played chain, which in the second case, just when enabled(like on ableton)

### Your setup
Win10 , Apollo 1.0.7

**Comment by mat1jaczyyy** [comment] 2019-08-28 12:19
Duplicate of #106. If an issue is closed with wontfix, don't feel bad to comment on it expressing why you think we should still have it :)

**Closed by mat1jaczyyy** 2019-08-28 12:19 UTC
Labels: duplicate, enhancement, ui
