### ISSUE TITLE
Shift Deleting Multiple Frames of a light effect

### ISSUE THREAD

**Issue by TheSillySpy** [mat1jaczyyy/apollo-studio#142] opened 2019-06-15 03:22 UTC
### Is your feature request related to a problem? Please describe.
Tried playing around with deleting multiple frames. You are able to do this with the right click delete option but I realized that it wasn't a feature with the delete key.

### Describe the solution you'd like
Have it so that you are able to highlight multiple frames and use the delete key to delete multiple frames.

### Additional context
Apollo Beta Version 11

**Comment by mat1jaczyyy** [comment] 2019-06-16 01:59
This issue is a duplicate of #137, as the reasoning for it comes from the same cause. It will be fixed as part of that issue.

**Closed by mat1jaczyyy** 2019-06-16 01:59 UTC
Labels: duplicate
