### ISSUE TITLE
LED leftovers with Fade->Copy

### ISSUE THREAD

**Issue by kangalioo** [mat1jaczyyy/apollo-studio#377] opened 2020-06-23 09:24 UTC
### Description
I have a chain with a Fade and a Copy device. When pressing a button on the Launchpad, the fade plays as expected - but after the fade, some of the LEDs randomly remain ever so slightly lit.

See here: https://youtu.be/iSMd46zDbWM

### To Reproduce
1. [Download this chain](https://drive.google.com/file/d/1REtUR3FcKLM87yoM9HBmtOqqJaLFVby9/view?usp=sharing):
![Screenshot_20200623_111648](https://user-images.githubusercontent.com/21220820/85385824-0a644080-b543-11ea-8b87-2902c307578e.png)
2. Press a key on your Launchpad

### Expected behavior
I expect there to be no remains.

### Your setup
Launchpad MK2, Linux, a4b68a80

**Comment by mat1jaczyyy** [comment] 2020-06-23 09:45
Dupe of #138

**Closed** 2020-06-23 20:40 UTC
Labels: bug, duplicate
