### ISSUE TITLE
Unable to write in the "author" panel

### ISSUE THREAD

**Issue by BattaNico** [mat1jaczyyy/apollo-studio#285] opened 2019-10-24 20:34 UTC
### Description
I can't write anything in the info box in Apollo where is the "author" 

### To Reproduce
Just open Apollo and try to write on the author tab

### Expected behavior
To write what I want

### Your setup
Win 10 and Apollo 1.1.2

**Comment by mat1jaczyyy** [comment] 2019-10-24 21:17
This is a duplicate of #282.

**Closed by mat1jaczyyy** 2019-10-24 21:17 UTC
Labels: bug
