### ISSUE TITLE
Crashes whenever I click on onscreen launchpad (probably heaven i tried with 1.5.0, 1.7.0, and 1.8.4)

### ISSUE THREAD

**Issue by awesome-coder-d** [mat1jaczyyy/apollo-studio#435] opened 2021-04-28 00:42 UTC
### Description
Apollo crashes whenever I click on the onscreen launchpad preview.

### To Reproduce
Open Apollo, go in preferences window, click on Launchpad preview

### Expected behavior
The rainbow preview effect shows up.
### Your setup
macOS 11.0 Big Sur, Apollo 1.8.4

### Additional context

https://user-images.githubusercontent.com/72720108/116329288-dfa8d100-a77f-11eb-9df9-f8acc03fd39c.mov

**Comment by WhosPix3l** [comment] 2021-04-28 00:50
dupe of #390, #403
pls dont make issues about bugs that have been reported thanks

**Comment by mat1jaczyyy** [comment] 2021-04-28 01:07
^ what he said
although a bimonthly reminder that i should work on this doesn't hurt

**Closed by mat1jaczyyy** 2021-04-28 01:07 UTC
Labels: bug
