### ISSUE TITLE
gif crash

### ISSUE THREAD

**Issue by r3apst3p** [mat1jaczyyy/apollo-studio#90] opened 2019-05-20 18:01 UTC
![giphy](https://user-images.githubusercontent.com/48379113/58042079-61c6fe80-7b42-11e9-9f98-4156f2dd767b.gif)

**Comment by mat1jaczyyy** [comment] 2019-05-20 18:08
Seems to be a duplicate of #89.

**Closed by mat1jaczyyy** 2019-05-20 18:08 UTC
Labels: duplicate
