### ISSUE TITLE
When copy pasting a lot of chains, sometimes apollo stops launchpad ouput afterwards

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [mat1jaczyyy/apollo-studio#421] opened 2020-12-24 11:54 UTC
### Description
When copying a lot of chains and pasting them into another group, apollo stops outputting lights to the launchpad after updating UI, only re-opening the project fixes the issue, no need to restart apollo completely. Also, I should note that **ANY** lights play, not only the chains I just pasted, all the lights from the project do not play!

### To Reproduce
Create a normal 8-page setup in apollo like shown in the tutorial video (mat1jaczyyy's channel) and insert at least 20 chains with pretty heavy effect chains (maybe less, haven't tried with less than that, maybe it depends on how heavy the chains are), then copy all of those and paste to another group (page), then try to play any of the effects using the launchpad, they will not display. After re-opening the project it goes back to normal. 

### Expected behavior
Apollo should paste the chains like normal and continue playing the lights as normal, without disabling the output.

### Your setup
OS: Windows 10 Pro - 64bit (update 20H2)
Apollo Ver: 1.8.3
Launchpad: Pro MK1

### Additional context
Haven't tried to reproduce on mac as I don't own one. The problem appears on my windows machine running the latest build of apollo and windows (at least when posting the issue)

**Comment by mat1jaczyyy** [comment] 2020-12-24 12:11
attach chains and files that cause this to easily repro, i cant guess what youre doing

**Comment by mat1jaczyyy** [comment] 2020-12-25 01:24
most likely a dupe of #413

**Comment by mat1jaczyyy** [comment] 2021-01-29 19:45
dupe #413

**Closed by mat1jaczyyy** 2021-01-29 19:45 UTC
Labels: bug, duplicate
