### ISSUE TITLE
Frozen lights after pasting huge item

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/apollo-studio#413] opened 2020-10-31 20:34 UTC
### Description
While copying and pasting the whole "page" of lights (60-70 chains or so), Apollo takes hella long just to paste it, but after minute or so waiting, Apollo unfreezes.. but just the ui. Lights are completly frozen and you cannot play anything. You have to restart to fix it.

### To Reproduce
Create a project with 70ish chains, than copy and paste the whole "page" of lights.

### Expected behavior
not to do that lmao

### Your setup
win 10, 1.8.3

### Additional context
ik its a dupe but i must submit it aaaaaaaaaaaa

**Comment by Brendonovich** [comment] 2020-10-31 20:51
please provide repro file thx

**Comment by YarostheLaunchpadder** [comment] 2020-12-24 11:55
Oh, I reported a similar issue #421
Maybe that will help diagnose the issue

**Comment by mat1jaczyyy** [comment] 2020-12-25 01:24
@Tuchan @YarostheLaunchpadder please provide files and steps that can easily reproduce this

**Comment by Tuchan** [comment] 2020-12-28 13:58
Idk how I completely forgot about that... sorry for causing problems, here is the file:
https://cdn.discordapp.com/attachments/713443705528254516/793115194568998922/nightmares.approj

To repro, basically copy one of these
![obraz](https://user-images.githubusercontent.com/43300571/103219133-2d6e1380-491d-11eb-982d-311ff1377bdf.png)

**Comment by mat1jaczyyy** [comment] 2021-01-29 19:04
just tried and i cant repro w10 1.8.3

**Comment by mat1jaczyyy** [comment] 2021-01-29 19:46
Turns out the "Frozen" lights was Fade device not regenerating. Dupe of #422.

**Closed by mat1jaczyyy** 2021-01-29 19:46 UTC
Labels: bug, help wanted
