### ISSUE TITLE
(macOS High Sierra+) Pattern Import does not work

### ISSUE THREAD

**Issue by RealAsianNoodles** [mat1jaczyyy/apollo-studio#105] opened 2019-05-28 12:37 UTC
### Description
In the pattern module, the import function for MIDI files is broken on macOS Mojave 10.14.5. Program does not freeze or stop responding - nothing occurs. Repeatedly attempting to import makes no difference. 

### To reproduce
^^^ try import a MIDI to pattern

### Expected behaviour
No crash

### Screenshot
why 

### Your setup
macOS Mojave 10.14.5, official Apple hardware, release version Apollo-b4

### Additional context
no context

**Comment by mat1jaczyyy** [comment] 2019-05-28 12:39
Can't reproduce on Sierra (10.12.6). Any chance there's a log or error of sorts?

**Comment by RealAsianNoodles** [comment] 2019-05-28 12:45
**Error message:**

Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff957073d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1a3b5bf50). One of the two will be used. Which one is undefined.

**Comment by mat1jaczyyy** [comment] 2019-05-28 12:49
Seems unrelated to Apollo, googling suggests this shouldn't stop the process of opening a file. Need to reproduce locally, gonna be tough to find access to a 10.13+ machine.

**Comment by mat1jaczyyy** [comment] 2019-06-07 11:28
Just tried on a 10.14.5 machine, I do get the error message logged to the console, however the MIDI file proceeds to load perfectly fine. Can't reproduce, can't fix.

**Comment by mat1jaczyyy** [comment] 2019-06-07 13:02
Conclusion - most likely an issue with the user's setup, rather than Apollo itself. Closing.

**Comment by mat1jaczyyy** [comment] 2019-06-15 11:59
Reopening because we should throw an error message if we can't read the file.

**Comment by mat1jaczyyy** [comment] 2019-06-20 02:14
Fixed by 47eb198.

**Closed by mat1jaczyyy** 2019-06-20 02:14 UTC
Labels: bug, device
