### ISSUE TITLE
Apollo crashes when clicking on Frames in Pattern Editor

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [mat1jaczyyy/apollo-studio#276] opened 2019-10-10 17:50 UTC
### Description
MINOR BUG:
Today I updated to the new 1.1.1 Apollo Studio Release, when I start the program, a window similiar to cmd (conhost it windows) comes up. I tried to close it, and it closes apollo.

MAJOR BUG:
I was designing my light effect with pattern device, then Apollo crashed, I reopened it, clicked restore project. Played the finished part of it, then I needed to continue with the light effects, I opened again the pattern device (the same I was working on when it crashed) and it crashed again, and again…

### To Reproduce
I did not tried yet with other devices. Just designing an effect in pattern device, produces crashes

### Expected behavior
I hope this bug will be fixed, BUT FOR NOW:

HOW CAN I DOWNLOAD A PREVOUS VERSION OF APOLLO STUDIO?

### Your setup
Windows 10 Pro 64-bit
Intel Core i7 4770K @ 3.50GHz
8,00GB Single-Channel DDR3

### Additional context
![Crashes folder](https://user-images.githubusercontent.com/54041533/66593388-2d0e1f00-eb97-11e9-951e-e7c431eef79e.PNG)

![CMD](https://user-images.githubusercontent.com/54041533/66593396-30a1a600-eb97-11e9-93c8-7c246ee69f92.PNG)

Thank You!
Yaros

**Comment by mat1jaczyyy** [comment] 2019-10-11 00:11
In the future, please report different bugs in separate issues, not with "Minor bug" and "Major bug" in your description. Additionally please use a descriptive title so it's easy to identify an issue when scrolling through the list.

As for your actual report, the minor bug is a dupe of #275. Please check for existing issues, especially if recently closed, before reporting issues. This issue has already been fixed in the master codebase.

The major bug is something I think I've fixed locally, but must have forgotten to push the commit to the codebase. I'll use this issue to log that specific problem.

To download a previous version, scroll down in the Releases page.

**Comment by mat1jaczyyy** [comment] 2019-10-11 00:12
Closed by accident.

**Closed** 2019-10-11 09:23 UTC
Labels: bug, device
